### ISSUE TITLE
[meta] Publish a revised Candidate Recommendation

### ISSUE THREAD

**Issue by anssiko** [w3c/html-media-capture#14]
On [today's call][1] we decided to publish a revised Candidate Recommendation.

I've staged a snapshot (work in progress):

* [HTML Media Capture W3C Candidate Recommendation 30 May 2017][2]

This snapshot will be updated automatically when #13 lands. We can adjust the publication date as needed, but in order to stick with the current PR entrance date of July 6, we should publish this revised CR before 6 June.

***

Per the [process for revising a CR][3], the group needs to address the following requirements:

- [x] must show that the revised specification meets all Working Group requirements, or explain why the requirements have changed or been deferred,
- [x] must specify the deadline for further comments, which must be at least four weeks after publication, and should be longer for complex documents,
- [ ] must document the changes since the previous Candidate Recommendation,
- [x] must show that the proposed changes have received wide review, and
- [x] may identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.

@fhirsch @dontcallmedom, am I right in assuming we do not need a new wide review? I took an action to document the changes since the previous Candidate Recommendation to tick the last remaining box, after which @fhirsch you could issue a CfC to publish.

[1]: https://www.w3.org/2017/05/18-dap-minutes.html#item03
[2]: https://w3c.github.io/html-media-capture/?specStatus=CR;previousMaturity=CR;previousPublishDate=2017-05-04/;crEnd=2017-06-27;publishDate=2017-05-30
[3]: https://www.w3.org/2017/Process-20170301/#revised-cr

**Comment by anssiko** [comment]
(The question regarding wide review was a copy-paste from another issue from where I copied the process requirements over, please ignore that.)

**Comment by anssiko** [comment]
@fhirsch @dontcallmedom, please take a look at the staged snapshot in https://github.com/w3c/html-media-capture/issues/14#issue-230419409 that has now been updated with the changes in #13 that addressed issue #12.

Questions:

* Is 30 May 2017 a good publication date?
* OK with the following changes since?

>Since Candidate Recommendation 04 May 2017, the capture IDL attribute was changed from an enumeration into a DOMString. This change aligns this specification with the HTML specification changes that removed the IDL enumeration reflection.

See also the [HTML diff] from the previous CR (this diff does not include the right publication date yet and the HTML references need to be patched manually -- will do that when all other things have been settled to avoid tedious manual work).

If all looks good, @fhirsch could you please issue a CfC to publish a revised CR so that we can keep the original PR schedule. Thanks!

[HTML diff]: http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FCR-html-media-capture-20170504%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Frawgit.com%252Fw3c%252Fhtml-media-capture%252Fgh-pages%252Findex.html%253FspecStatus%253DCR%253BshortName%253Dhtml-media-capture

**Comment by anssiko** [comment]
Publication ready static snapshot at:

https://w3c.github.io/html-media-capture/releases/CR4.html

**Comment by anssiko** [comment]
@fhirsch, should the snapshot requires further changes, I'll authorize @dontcallmedom and @xfq edit the snapshot as needed. As is, the snapshot passes https://www.w3.org/pubrules/ and https://validator.w3.org/checklink with false negatives (linkcheck does not understand HTML multipage redirects).

**Comment by dontcallmedom** [comment]
@anssiko the links to the HTML specs go to HTML LS whereas the references are to HTML51 - that seems inconsistent

**Comment by anssiko** [comment]
I tried s/!HTML#/!HTML51#/g but it broke all the links.

Probably related: https://github.com/w3c/respec/issues/1180

@dontcallmedom, can you look into this, perhaps fix manually prior to publication?

**Comment by dontcallmedom** [comment]
I'm looking into a patch for respec, and failing that, will do the manual fix prior to publication.

**Comment by anssiko** [comment]
Regarding patching this in respec, it appears some fragment identifiers have also changed from HTML -> HTML51, so would need two mapping tables, one for subpages and another for the fragment identifiers.

For example:

HTML LS: https://html.spec.whatwg.org/multipage/#file-upload-state-(type=file)
redirects via `link-fixup.js` to https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type%3Dfile)

HTML51: https://www.w3.org/TR/html51/sec-forms.html#file-upload-state-typefile

Another example:

HTML LS: https://html.spec.whatwg.org/multipage/#reflect
-> https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflect
HTML51: https://www.w3.org/TR/html51/infrastructure.html#reflection

HTML LS uses https://html.spec.whatwg.org/link-fixup.js that loads fragments from https://html.spec.whatwg.org/multipage/fragment-links.json

... sounds like a slightly involved patch. Anyway, thanks for looking into this!

**Comment by dontcallmedom** [comment]
given that my respec patch is about to be merged, I'll instead patch the source document to refer to HTML51 (HTML52?) and adapt the paths/fragment identifiers as needed

**Comment by anssiko** [comment]
Works for me, thanks!

**Comment by dontcallmedom** [comment]
#16 does this - could you regenerate a staged CR based on this @anssiko ?

Note that I also added a normative ref to custom-elements since we use its `[CEReactions]` extended attribute - @xfq we may need to amend the transition request to point that out.

**Comment by anssiko** [comment]
Submitted a new PR with regenerated CR4 snapshot at #17.

**Comment by anssiko** [comment]
Updated the CR4 snapshot, thanks @dontcallmedom for the fixes to respec. Should be ready to publish now.

cc @xfq

**Comment by anssiko** [comment]
I noticed https://w3c.github.io/html-media-capture/releases/CR4.html did not ship yesterday since https://www.w3.org/TR/html-media-capture/ still points to the 04 May 2017 CR.

@xfq, @dontcallmedom, please let me know if you'd like me to update the CR4 snapshot, but also feel free to do minor adjustments such as updating the publication date without my involvement.

Looking forward to shipping the revised CR soon!

**Comment by dontcallmedom** [comment]
indeed, we're still waiting for Director approval; I think we should be able to prepare an updated snapshot when we know the right publication date.

**Comment by anssiko** [comment]
W3C Candidate Recommendation 31 August 2017 published:

https://www.w3.org/TR/2017/CR-html-media-capture-20170831/

Thanks @dontcallmedom @xfq for your help.
