### ISSUE TITLE
[meta] Prepare a revised Candidate Recommendation snapshot

### ISSUE THREAD

**Issue by anssiko** [w3c/html-media-capture#9]
- [x] Add changes since previous published version (text summary, and HTML diff)
- [x] Use publication date target of April 20th, 2017
- [x] Add updated implementation report
- [x] CR end date 8 weeks from publication

**Comment by anssiko** [comment]
Thanks @dontcallmedom for volunteering to help with the snapshot preparation.

**Comment by dontcallmedom** [comment]
I've made some progress, but haven't been able to complete this in a satisfactory manner:
* ReSpec makes the wrong link for CEReactions - I've prepared a [pull request to get that fixed upstream](https://github.com/w3c/respec/pull/1179), but I'm not sure when that will land; maybe better fixing this manually for the time being?
* We're linking to HTML LS, but I think HTML 5.1 has all we need, so we probably should do that instead; one issue is that I haven't found [how to use `data-cite` on sub-pages](https://github.com/w3c/respec/issues/1180); again, maybe a better of fixing manually

I added a customized paragraph in the SOTD to list our changes, updated a few of the metadata; but didn't finish the export and generation of the diff due to the above.

(I didn't change our link to the implementation report since the wiki page already in there has the right link to the actual report)

**Comment by anssiko** [comment]
CR3 snapshot prepared, addressed issues identified in https://github.com/w3c/html-media-capture/issues/9#issuecomment-292522548 as proposed:

[CR3.html][1]
[CR3-diff.html][2]
[images/capture-api-file-picker-concept.png][3]

Passes [Pubrules][4] and [Link Checker][5].

[1]: https://w3c.github.io/html-media-capture/releases/CR3.html
[2]: https://w3c.github.io/html-media-capture/releases/CR3-diff.html
[3]: https://w3c.github.io/html-media-capture/releases/images/capture-api-file-picker-concept.png
[4]: https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fhtml-media-capture%2Freleases%2FCR3.html&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004
[5]: http://validator.w3.org/checklink?uri=https://w3c.github.io/html-media-capture/releases/CR3.html&recursive=on

**Comment by anssiko** [comment]
Updated the snapshot per review comments from @fhirsch. Most notably, changes the publication date to 04 May 2017.

(For details, see https://github.com/w3c/html-media-capture/pull/10/commits/581a5338f70986062dbab5e85a38eff6dfa28bcf)

**Comment by anssiko** [comment]
Landed a fix https://github.com/w3c/html-media-capture/commit/e2424bb8dcbce7c479651ccc02a271c043e2a2ee
